"""
Codici di errore condivisi da tutti i service del gioco.
"""

FORMATION_NOT_FOUND = "FORMATION_NOT_FOUND"

INVALID_SLOT = "INVALID_SLOT"

PLAYER_NOT_FOUND = "PLAYER_NOT_FOUND"

PLAYER_NOT_IN_SQUAD = "PLAYER_NOT_IN_SQUAD"

PLAYER_ALREADY_STARTER = "PLAYER_ALREADY_STARTER"

INCOMPATIBLE_POSITION = "INCOMPATIBLE_POSITION"

SAVE_ERROR = "SAVE_ERROR"

UNKNOWN_ERROR = "UNKNOWN_ERROR"